---
AWSTemplateFormatVersion: 2010-09-09
Description: >-
  AWS DevOps Challenge - 1
Parameters:
  KeyName:
    Type: 'AWS::EC2::KeyPair::KeyName'
    Description: The EC2 Key Pair to allow SSH access to the instances
    ConstraintDescription: must be the name of an existing EC2 KeyPair.
  InstanceType:
    Description: EC2 instance type
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t2.small
      - t2.medium
      - t2.large
    ConstraintDescription: must be a valid EC2 instance type.
  VpcId:
    Type: "AWS::EC2::VPC::Id"
    Description: VpcId of your existing Virtual Private Cloud (VPC)
    ConstraintDescription: must be the VPC Id of an existing Virtual Private Cloud.
  VpcSubnets:
    Type: "List<AWS::EC2::Subnet::Id>"
    Description: The list of SubnetIds in your Virtual Private Cloud (VPC)
    ConstraintDescription: must be a list of at least two existing subnets associated with at least two different availability zones. They should be residing in the selected Virtual Private Cloud.
Mappings:
  AWSRegion2AMI:
    us-east-1: 
      HVM64: ami-0080e4c5bc078760e
    us-west-2: 
      HVM64: ami-01e24be29428c15b2
    us-west-1: 
      HVM64: ami-0ec6517f6edbf8044
    eu-west-1: 
      HVM64: ami-08935252a36e25f85
    eu-west-2: 
      HVM64: ami-01419b804382064e4
    eu-west-3: 
      HVM64: ami-0dd7e7ed60da8fb83
    eu-central-1: 
      HVM64: ami-0cfbf4f6db41068ac
    eu-north-1: 
      HVM64: ami-86fe70f8
    ap-northeast-1: 
      HVM64: ami-00a5245b4816c38e6
    ap-northeast-2: 
      HVM64: ami-00dc207f8ba6dc919
    ap-northeast-3: 
      HVM64: ami-0b65f69a5c11f3522
    ap-southeast-1: 
      HVM64: ami-05b3bcf7f311194b3
    ap-southeast-2: 
      HVM64: ami-02fd0b06f06d93dfc
    ap-south-1: 
      HVM64: ami-0ad42f4f66f6c1cc9
    us-east-2: 
      HVM64: ami-0cd3dfa4e37921605
    ca-central-1: 
      HVM64: ami-07423fb63ea0a0930
    sa-east-1: 
      HVM64: ami-05145e0b28ad8e0b2
Resources:
  LaunchConfiguration:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      InstanceMonitoring: false
      ImageId: !FindInMap 
        - AWSRegion2AMI
        - !Ref 'AWS::Region'
        - HVM64
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      SecurityGroups: 
      - Ref: SecurityGroup
      IamInstanceProfile: !Ref 'InstanceProfile'
      UserData:
        "Fn::Base64":
          !Sub |
            #!/bin/bash -xe
            yum update -y aws-cfn-bootstrap
            aws ec2 associate-address --allocation-id ${EIP.AllocationId} --instance-id $(curl -s http://169.254.169.254/latest/meta-data/instance-id) --allow-reassociation --region ${AWS::Region}
            /opt/aws/bin/cfn-signal -e $? --stack ${AWS::StackName} --resource AutoScalingGroup --region ${AWS::Region}
  AutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      VPCZoneIdentifier: !Ref VpcSubnets
      LaunchConfigurationName:
        Ref: LaunchConfiguration
      MinSize: '1'
      MaxSize: '1'
      Tags:
        - Key: Owner
          PropagateAtLaunch: true
          Value: Dimag
    CreationPolicy:
      ResourceSignal:
        Timeout: PT15M
        Count: '1'
  SecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Enable SSH access via port 22
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: '0.0.0.0/0'
      Tags:
        - Key: Owner
          Value: Dimag
  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties: 
      Roles: 
        - !Ref InstanceProfileRole
  InstanceProfileRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: ec2eip
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - ec2:AssociateAddress
                Resource: '*'
      Tags:
        - Key: Owner
          Value: Dimag
  EIP:
    Type: AWS::EC2::EIP
    Properties:
      Tags:
        - Key: Owner
          Value: Dimag
Outputs:
  EIP:
    Value: !Ref 'EIP'